### ISSUE TITLE
Disable "long touch to select" on mobile

### ISSUE THREAD

**Issue by pobch** [pobch/react-diagram#45]
### Steps to reproduce
1. Open the website on mobile
2. Press long touch anywhere in the canvas
3. BUG: the whole page will be selected/hi-lighted (similar to selecting the text)

### Possible solution
```css
body {
  user-select: none;
}
textarea, input {
  user-select: revert;
}
```
